name: .NET Build

on:
  push:
    branches:
      - main  # This can be any branch you're working on
  pull_request:
    branches:
      - main  # This will trigger the action on new or updated PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can use other runners, but we'll use Ubuntu here

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup .NET SDK on the runner
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Make sure to specify the .NET version you're using

      # Step 3: Restore dependencies (download packages specified in .csproj or .sln)
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: Build the project
      - name: Build project
        run: dotnet build --configuration Release --no-restore
