name: .NET Build and Test

on:
  push:
    branches:
      - main  # You can change 'main' to the default branch you're using
  pull_request:
    branches:
      - main  # This triggers the workflow for pull requests to the 'main' branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Using Ubuntu for this example, but you can choose other environments (e.g., windows-latest)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # This checks out the code from the repository

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'  # Replace with your required .NET version

      - name: Restore dependencies
        run: dotnet restore ClassLibraryProjects/StringLibrary/StringLibrary.csproj  # This restores NuGet dependencies

      - name: Build project
        run: dotnet build ClassLibraryProjects/StringLibrary/StringLibrary.csproj --configuration Release --no-restore  # This builds the project

      - name: Run tests
        run: dotnet test ClassLibraryProjects/StringLibraryTest/StringLibraryTest.csproj --configuration Release --no-build --logger "console;verbosity=detailed"  # Run tests using MSTest
